/**
 * README written into `outputs/<run>/debug/` when DEBUG_MODE=true.
 *
 * Audience: a human — or an AI — asked to root-cause a failed or odd run
 * from the debug bundle alone, so it documents the record schema, the
 * correlation keys and the cross-references to the other run artifacts.
 */

export function renderDebugTraceReadme(opts: { maxFieldChars: number }): string {
    const clipNote = opts.maxFieldChars > 0
        ? `Strings longer than ${opts.maxFieldChars} characters (\`DEBUG_TRACE_MAX_FIELD_CHARS\`) keep their head and tail around a \`…[debug-trace: N chars elided of M]…\` marker; command output keeps more of the tail, where errors print.`
        : 'Strings are not clipped (`DEBUG_TRACE_MAX_FIELD_CHARS=0`).';

    return [
        '# AgenticDevTeam — debug trace',
        '',
        'This folder exists because the run was started with `DEBUG_MODE=true`. It records everything',
        'the pipeline did, in order, so a failure can be root-caused without re-running it.',
        '',
        '## Files',
        '',
        '| File | Contents |',
        '|------|----------|',
        '| `trace.jsonl` | The complete chronological timeline — one JSON record per line, ordered by `seq`. |',
        '| `errors.jsonl` | Every failure record, copied verbatim from `trace.jsonl` (same `seq`). Start here. |',
        '| `summary.json` | Counts and failures per kind, slowest operations, LLM stats per agent, command stats per program. Written at finalize and on crash/shutdown. |',
        '| `environment.json` | Runtime, app version + git commit, run metadata and the effective configuration (secret values masked). |',
        '',
        'Related artifacts in the parent run directory (`..`):',
        '',
        '- `run.log` — human-readable log (every line is also in `trace.jsonl` as `kind: "log"`).',
        '- `ledger.jsonl`, `run-report.md`, `run-diagnosis.md` — pipeline decisions and the automated diagnosis.',
        '- `full-responses/` — the complete, unclipped conversation of every agent invocation; `kind: "response"` records name the file.',
        '- `state.json`, `run-manifest.json`, `token-usage.json` — final state, outcome and token accounting.',
        '',
        '## Record envelope',
        '',
        'Every record carries `seq` (order within this session), `t` (ISO timestamp), `runId`, `kind` and usually `event`;',
        'when known also `phase` (graph node), `branch` (PR-workflow branch) and `agentId`. A continued run appends a new',
        'session to the same files: `seq` restarts, `runId` changes and the session begins with a `run`/`init` record.',
        '',
        '## Record kinds',
        '',
        '| kind | event | Fields |',
        '|------|-------|--------|',
        '| `run` | `init`, `crash` | Run metadata; crash `context` and `error`. |',
        '| `node` | `start` / `end` / `error` | `node`; `vitals` (phase, iteration, counts) on entry; `update` summary and `durationMs` on exit; `error` with stack. |',
        '| `route` | `decision` | `from`, `to` and the `vitals` that drove the conditional edge. |',
        '| `llm` | `start` / `end` / `error` | `llmRunId` links the three. start: `agentId`, `model`, `invocationId`, `threadId`, `step`, `params`, `tools`, `messages`. end: `output` (`text`, `blocks`, `toolCalls`, `thinking`), `usage`, `stopReason`, `responseModel`. error: provider `status`, `body`, `headers`. |',
        '| `tool` | `end` / `error` | `agentId`, `tool`, `toolCallId` (the `id` in the preceding `llm` end `toolCalls`), `args`, `result` exactly as the agent saw it, `ok`, loop-guard budget `usage`. |',
        '| `exec` | `start` (async only) / `end` / `error` | `program`, `cmd`, `cwd`, `timeoutMs`, `stdin`, `exitCode`, `signal`, `timedOut`, `stdout`, `stderr`, `caller` (source `file:line`). `probe: true` marks an expected non-zero exit (kept out of `errors.jsonl`). |',
        '| `http` | `end` / `error` | GitHub API (live or local stand-in): `service`, `method`, `route`, `params`, `status`, `response`. |',
        '| `docker` | `end` / `error` | `op` (build / run / health / stop), image or container, `logs`. |',
        '| `retry` | `attempt` / `giveup` | `label`, `attempt`, `maxAttempts`, `delayMs`, `error`. |',
        '| `event` | — | Event-bus `type` and `payload` (agent:start/end, pr:*, gate:result, …). |',
        '| `ledger` | — | `entry` — the same object appended to `../ledger.jsonl`. |',
        '| `response` | `logged` | `file` in `../full-responses/` holding the full agent conversation. |',
        '| `log` | — | `level`, `tag`, `message` — every logger line, including DEBUG. |',
        '| `crash` | `uncaughtException` / `unhandledRejection` / `signal` | Process-level failure. |',
        '',
        '### LLM message de-duplication',
        '',
        '`llm` `start` records hold the exact request the model received (after history compaction). A message is stored in',
        'full, with a `hash`, the first time an agent instance sends it; later requests reference it as `{ "ref": "<hash>" }`.',
        'Resolve a `ref` by searching earlier `llm` records of the same `agentId` for `"hash":"<hash>"`. A respawned agent',
        'starts a fresh scope, so its first request is self-contained.',
        '',
        '## Redaction and clipping',
        '',
        '- Credentials are replaced with `***REDACTED***` everywhere: GitHub tokens, API keys, auth headers, URL credentials',
        '  and the exact values of the configured secrets.',
        '- Prompts, requirements, source code and tool output are NOT redacted — treat this folder as confidential.',
        `- ${clipNote} Complete agent conversations are in \`../full-responses/\`.`,
        '',
        '## Suggested analysis workflow',
        '',
        '1. Read `summary.json` for the shape of the run, then `errors.jsonl`.',
        '2. For each relevant failure, read the records around its `seq` in `trace.jsonl`.',
        '3. Follow the links: `toolCallId` ↔ `llm` `toolCalls[].id`; `llmRunId` start ↔ end; `invocationId` ↔',
        '   `../full-responses/index.jsonl` and `../token-usage.json`; `caller` → the source line that ran a command.',
        '4. Use `node`/`route` for control-flow questions, `exec` for git/build/test failures, `llm`/`tool` for agent behaviour.',
        '',
        '### Prompt to paste along with this folder',
        '',
        '> You are debugging a run of AgenticDevTeam, a LangGraph multi-agent software-delivery pipeline. The attached',
        '> `debug/` folder contains `trace.jsonl` (chronological JSON records), `errors.jsonl` (failures, same `seq`),',
        '> `summary.json` and `environment.json`; `README.md` documents the schema. Identify the root cause of',
        '> <describe the symptom>. Cite the `seq` of every record that supports each step of your reasoning, separate',
        '> root causes from downstream symptoms, and propose concrete code or configuration fixes.',
        '',
    ].join('\n');
}
